//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WINgestion.SRgestion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequerimientoWCF", Namespace="http://schemas.datacontract.org/2004/07/WCFgestion.Modelo")]
    [System.SerializableAttribute()]
    public partial class RequerimientoWCF : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodCeCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodClasificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodComponenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodPosPreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodTipoAdquisicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodTipoGastoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CcodUnidadMedidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CnumRequerimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DfecRequerimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FcantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FimporteTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FprecioUnitarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FstockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IidRequerimiento_CabeceraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IidRequerimiento_DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IidRequerimiento_Detalle_BienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IidRequerimiento_Detalle_ServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TespecificacionTecnica_BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TespecificacionTecnica_SField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TnotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cCodFuenteFinanciamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomCeCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomClaseGastoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomClasificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomCortoProyectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomFuenteFinanciamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomPosPreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomServicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomTipoAdquisicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vNomUnidadMedidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodCeCo {
            get {
                return this.CcodCeCoField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodCeCoField, value) != true)) {
                    this.CcodCeCoField = value;
                    this.RaisePropertyChanged("CcodCeCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodClasificador {
            get {
                return this.CcodClasificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodClasificadorField, value) != true)) {
                    this.CcodClasificadorField = value;
                    this.RaisePropertyChanged("CcodClasificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodComponente {
            get {
                return this.CcodComponenteField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodComponenteField, value) != true)) {
                    this.CcodComponenteField = value;
                    this.RaisePropertyChanged("CcodComponente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodMaterial {
            get {
                return this.CcodMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodMaterialField, value) != true)) {
                    this.CcodMaterialField = value;
                    this.RaisePropertyChanged("CcodMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodPosPre {
            get {
                return this.CcodPosPreField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodPosPreField, value) != true)) {
                    this.CcodPosPreField = value;
                    this.RaisePropertyChanged("CcodPosPre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodProyecto {
            get {
                return this.CcodProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodProyectoField, value) != true)) {
                    this.CcodProyectoField = value;
                    this.RaisePropertyChanged("CcodProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodServicio {
            get {
                return this.CcodServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodServicioField, value) != true)) {
                    this.CcodServicioField = value;
                    this.RaisePropertyChanged("CcodServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodTipoAdquisicion {
            get {
                return this.CcodTipoAdquisicionField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodTipoAdquisicionField, value) != true)) {
                    this.CcodTipoAdquisicionField = value;
                    this.RaisePropertyChanged("CcodTipoAdquisicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodTipoGasto {
            get {
                return this.CcodTipoGastoField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodTipoGastoField, value) != true)) {
                    this.CcodTipoGastoField = value;
                    this.RaisePropertyChanged("CcodTipoGasto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CcodUnidadMedida {
            get {
                return this.CcodUnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.CcodUnidadMedidaField, value) != true)) {
                    this.CcodUnidadMedidaField = value;
                    this.RaisePropertyChanged("CcodUnidadMedida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CnumRequerimiento {
            get {
                return this.CnumRequerimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.CnumRequerimientoField, value) != true)) {
                    this.CnumRequerimientoField = value;
                    this.RaisePropertyChanged("CnumRequerimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DfecRequerimiento {
            get {
                return this.DfecRequerimientoField;
            }
            set {
                if ((this.DfecRequerimientoField.Equals(value) != true)) {
                    this.DfecRequerimientoField = value;
                    this.RaisePropertyChanged("DfecRequerimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Fcantidad {
            get {
                return this.FcantidadField;
            }
            set {
                if ((this.FcantidadField.Equals(value) != true)) {
                    this.FcantidadField = value;
                    this.RaisePropertyChanged("Fcantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FimporteTotal {
            get {
                return this.FimporteTotalField;
            }
            set {
                if ((this.FimporteTotalField.Equals(value) != true)) {
                    this.FimporteTotalField = value;
                    this.RaisePropertyChanged("FimporteTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FprecioUnitario {
            get {
                return this.FprecioUnitarioField;
            }
            set {
                if ((this.FprecioUnitarioField.Equals(value) != true)) {
                    this.FprecioUnitarioField = value;
                    this.RaisePropertyChanged("FprecioUnitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Fstock {
            get {
                return this.FstockField;
            }
            set {
                if ((this.FstockField.Equals(value) != true)) {
                    this.FstockField = value;
                    this.RaisePropertyChanged("Fstock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IidRequerimiento_Cabecera {
            get {
                return this.IidRequerimiento_CabeceraField;
            }
            set {
                if ((this.IidRequerimiento_CabeceraField.Equals(value) != true)) {
                    this.IidRequerimiento_CabeceraField = value;
                    this.RaisePropertyChanged("IidRequerimiento_Cabecera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IidRequerimiento_Detalle {
            get {
                return this.IidRequerimiento_DetalleField;
            }
            set {
                if ((this.IidRequerimiento_DetalleField.Equals(value) != true)) {
                    this.IidRequerimiento_DetalleField = value;
                    this.RaisePropertyChanged("IidRequerimiento_Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IidRequerimiento_Detalle_Bien {
            get {
                return this.IidRequerimiento_Detalle_BienField;
            }
            set {
                if ((this.IidRequerimiento_Detalle_BienField.Equals(value) != true)) {
                    this.IidRequerimiento_Detalle_BienField = value;
                    this.RaisePropertyChanged("IidRequerimiento_Detalle_Bien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IidRequerimiento_Detalle_Servicio {
            get {
                return this.IidRequerimiento_Detalle_ServicioField;
            }
            set {
                if ((this.IidRequerimiento_Detalle_ServicioField.Equals(value) != true)) {
                    this.IidRequerimiento_Detalle_ServicioField = value;
                    this.RaisePropertyChanged("IidRequerimiento_Detalle_Servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TespecificacionTecnica_B {
            get {
                return this.TespecificacionTecnica_BField;
            }
            set {
                if ((object.ReferenceEquals(this.TespecificacionTecnica_BField, value) != true)) {
                    this.TespecificacionTecnica_BField = value;
                    this.RaisePropertyChanged("TespecificacionTecnica_B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TespecificacionTecnica_S {
            get {
                return this.TespecificacionTecnica_SField;
            }
            set {
                if ((object.ReferenceEquals(this.TespecificacionTecnica_SField, value) != true)) {
                    this.TespecificacionTecnica_SField = value;
                    this.RaisePropertyChanged("TespecificacionTecnica_S");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tnota {
            get {
                return this.TnotaField;
            }
            set {
                if ((object.ReferenceEquals(this.TnotaField, value) != true)) {
                    this.TnotaField = value;
                    this.RaisePropertyChanged("Tnota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cCodFuenteFinanciamiento {
            get {
                return this.cCodFuenteFinanciamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.cCodFuenteFinanciamientoField, value) != true)) {
                    this.cCodFuenteFinanciamientoField = value;
                    this.RaisePropertyChanged("cCodFuenteFinanciamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomCeCo {
            get {
                return this.vNomCeCoField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomCeCoField, value) != true)) {
                    this.vNomCeCoField = value;
                    this.RaisePropertyChanged("vNomCeCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomClaseGasto {
            get {
                return this.vNomClaseGastoField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomClaseGastoField, value) != true)) {
                    this.vNomClaseGastoField = value;
                    this.RaisePropertyChanged("vNomClaseGasto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomClasificador {
            get {
                return this.vNomClasificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomClasificadorField, value) != true)) {
                    this.vNomClasificadorField = value;
                    this.RaisePropertyChanged("vNomClasificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomCortoProyecto {
            get {
                return this.vNomCortoProyectoField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomCortoProyectoField, value) != true)) {
                    this.vNomCortoProyectoField = value;
                    this.RaisePropertyChanged("vNomCortoProyecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomFuenteFinanciamiento {
            get {
                return this.vNomFuenteFinanciamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomFuenteFinanciamientoField, value) != true)) {
                    this.vNomFuenteFinanciamientoField = value;
                    this.RaisePropertyChanged("vNomFuenteFinanciamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomMaterial {
            get {
                return this.vNomMaterialField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomMaterialField, value) != true)) {
                    this.vNomMaterialField = value;
                    this.RaisePropertyChanged("vNomMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomPosPre {
            get {
                return this.vNomPosPreField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomPosPreField, value) != true)) {
                    this.vNomPosPreField = value;
                    this.RaisePropertyChanged("vNomPosPre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomServicio {
            get {
                return this.vNomServicioField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomServicioField, value) != true)) {
                    this.vNomServicioField = value;
                    this.RaisePropertyChanged("vNomServicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomTipoAdquisicion {
            get {
                return this.vNomTipoAdquisicionField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomTipoAdquisicionField, value) != true)) {
                    this.vNomTipoAdquisicionField = value;
                    this.RaisePropertyChanged("vNomTipoAdquisicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vNomUnidadMedida {
            get {
                return this.vNomUnidadMedidaField;
            }
            set {
                if ((object.ReferenceEquals(this.vNomUnidadMedidaField, value) != true)) {
                    this.vNomUnidadMedidaField = value;
                    this.RaisePropertyChanged("vNomUnidadMedida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRgestion.IWCFgestionE")]
    public interface IWCFgestionE {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_AñoProceso", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_AñoProcesoResponse")]
        System.Data.DataTable Combo_AñoProceso(string strCodCompañia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_AñoProceso", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_AñoProcesoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Combo_AñoProcesoAsync(string strCodCompañia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_CabeceraResponse")]
        Model.Requerimiento_Cabecera Recupera_Requerimiento_Cabecera(int intIdRequrimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_CabeceraResponse")]
        System.Threading.Tasks.Task<Model.Requerimiento_Cabecera> Recupera_Requerimiento_CabeceraAsync(int intIdRequrimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_CabeceraResponse")]
        Model.Requerimiento_Cabecera Graba_Requerimiento_Cabecera(Model.Requerimiento_Cabecera obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_CabeceraResponse")]
        System.Threading.Tasks.Task<Model.Requerimiento_Cabecera> Graba_Requerimiento_CabeceraAsync(Model.Requerimiento_Cabecera obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_CabeceraResponse")]
        int Modifica_Requerimiento_Cabecera(Model.Requerimiento_Cabecera obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_CabeceraResponse")]
        System.Threading.Tasks.Task<int> Modifica_Requerimiento_CabeceraAsync(Model.Requerimiento_Cabecera obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_CabeceraResponse")]
        int Elimina_Requerimiento_Cabecera(int intIdRequerimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Cabecera", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_CabeceraResponse")]
        System.Threading.Tasks.Task<int> Elimina_Requerimiento_CabeceraAsync(int intIdRequerimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Formulado_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Formulado_CentroCostoResponse")]
        System.Data.DataSet Lista_Formulado_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Formulado_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Formulado_CentroCostoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Formulado_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Disponible_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Disponible_CentroCostoResponse")]
        System.Data.DataSet Lista_Disponible_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Disponible_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Disponible_CentroCostoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Disponible_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_CentroCostoResponse")]
        System.Data.DataSet Lista_Ejecutado_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_CentroCostoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Ejecutado_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Comprometido_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Comprometido_CentroCostoResponse")]
        System.Data.DataSet Lista_Comprometido_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Comprometido_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Comprometido_CentroCostoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Comprometido_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_CentroCostoResponse")]
        System.Data.DataSet Lista_EjecucionPresupuestal_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_CentroCostoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_EjecucionPresupuestal_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_ProyectoResponse")]
        System.Data.DataSet Lista_EjecucionPresupuestal_Proyecto(string strAñoProceso, string strCodProyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_EjecucionPresupuestal_ProyectoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_EjecucionPresupuestal_ProyectoAsync(string strAñoProceso, string strCodProyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_RequerimientoResponse")]
        System.Data.DataSet Formato_Requerimiento(string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_RequerimientoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Formato_RequerimientoAsync(string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_Requerido", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_RequeridoResponse")]
        System.Data.DataSet Lista_Requerimiento_Detalle_Requerido(Model.Formulacion_Saldo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_Requerido", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_RequeridoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Requerimiento_Detalle_RequeridoAsync(Model.Formulacion_Saldo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_Ejecutado", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_EjecutadoResponse")]
        System.Data.DataSet Lista_Requerimiento_Detalle_Ejecutado(Model.Formulacion_Saldo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_Ejecutado", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle_EjecutadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Requerimiento_Detalle_EjecutadoAsync(Model.Formulacion_Saldo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_DetalleResponse")]
        Model.Requerimiento_Detalle Recupera_Requerimiento_Detalle(int intIdRequrimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_DetalleResponse")]
        System.Threading.Tasks.Task<Model.Requerimiento_Detalle> Recupera_Requerimiento_DetalleAsync(int intIdRequrimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_DetalleResponse")]
        int Graba_Requerimiento_Detalle(Model.Requerimiento_Detalle obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_DetalleResponse")]
        System.Threading.Tasks.Task<int> Graba_Requerimiento_DetalleAsync(Model.Requerimiento_Detalle obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_DetalleResponse")]
        int Modifica_Requerimiento_Detalle(Model.Requerimiento_Detalle obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_DetalleResponse")]
        System.Threading.Tasks.Task<int> Modifica_Requerimiento_DetalleAsync(Model.Requerimiento_Detalle obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_DetalleResponse")]
        int Elimina_Requerimiento_Detalle(int intIdRequerimiento_Detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_DetalleResponse")]
        System.Threading.Tasks.Task<int> Elimina_Requerimiento_DetalleAsync(int intIdRequerimiento_Detalle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_DetalleResponse")]
        System.Data.DataSet Lista_Requerimiento_Detalle(string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_Detalle", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Requerimiento_DetalleResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Requerimiento_DetalleAsync(string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_Estado", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_EstadoResponse")]
        System.Data.DataSet Formato_Requerimiento_Estado(string strCodCentro_Gestor, string strEstado, string strCodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_Estado", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_EstadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Formato_Requerimiento_EstadoAsync(string strCodCentro_Gestor, string strEstado, string strCodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_Firma", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_FirmaResponse")]
        bool Formato_Requerimiento_Firma(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_Firma", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_FirmaResponse")]
        System.Threading.Tasks.Task<bool> Formato_Requerimiento_FirmaAsync(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_Ceco", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_CecoResponse")]
        System.Data.DataSet Formato_Requerimiento_Ceco(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_Ceco", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_CecoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Formato_Requerimiento_CecoAsync(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_DescarteFirma", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_DescarteFirmaResponse")]
        bool Formato_Requerimiento_DescarteFirma(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento, string strMotivoDescarte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_DescarteFirma", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_Requerimiento_DescarteFirmaResponse")]
        System.Threading.Tasks.Task<bool> Formato_Requerimiento_DescarteFirmaAsync(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento, string strMotivoDescarte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_BienResponse")]
        Model.Requerimiento_Detalle_Bien Recupera_Requerimiento_Detalle_Bien(int intIdRequrimiento_Detalle_Bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_BienResponse")]
        System.Threading.Tasks.Task<Model.Requerimiento_Detalle_Bien> Recupera_Requerimiento_Detalle_BienAsync(int intIdRequrimiento_Detalle_Bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_BienResponse")]
        int Graba_Requerimiento_Detalle_Bien(Model.Requerimiento_Detalle_Bien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_BienResponse")]
        System.Threading.Tasks.Task<int> Graba_Requerimiento_Detalle_BienAsync(Model.Requerimiento_Detalle_Bien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_BienResponse")]
        int Modifica_Requerimiento_Detalle_Bien(Model.Requerimiento_Detalle_Bien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_BienResponse")]
        System.Threading.Tasks.Task<int> Modifica_Requerimiento_Detalle_BienAsync(Model.Requerimiento_Detalle_Bien obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_BienResponse")]
        int Elimina_Requerimiento_Detalle_Bien(int intIdRequerimiento_Detalle_Bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_Bien", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_BienResponse")]
        System.Threading.Tasks.Task<int> Elimina_Requerimiento_Detalle_BienAsync(int intIdRequerimiento_Detalle_Bien);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_ServicioResponse")]
        Model.Requerimiento_Detalle_Servicio Recupera_Requerimiento_Detalle_Servicio(int intIdRequrimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento_Detalle_ServicioResponse")]
        System.Threading.Tasks.Task<Model.Requerimiento_Detalle_Servicio> Recupera_Requerimiento_Detalle_ServicioAsync(int intIdRequrimiento_Cabecera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_ServicioResponse")]
        int Graba_Requerimiento_Detalle_Servicio(Model.Requerimiento_Detalle_Servicio obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Graba_Requerimiento_Detalle_ServicioResponse")]
        System.Threading.Tasks.Task<int> Graba_Requerimiento_Detalle_ServicioAsync(Model.Requerimiento_Detalle_Servicio obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_ServicioResponse")]
        int Modifica_Requerimiento_Detalle_Servicio(Model.Requerimiento_Detalle_Servicio obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Modifica_Requerimiento_Detalle_ServicioResponse")]
        System.Threading.Tasks.Task<int> Modifica_Requerimiento_Detalle_ServicioAsync(Model.Requerimiento_Detalle_Servicio obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_ServicioResponse")]
        int Elimina_Requerimiento_Detalle_Servicio(int intIdRequerimiento_Detalle_Servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Elimina_Requerimiento_Detalle_ServicioResponse")]
        System.Threading.Tasks.Task<int> Elimina_Requerimiento_Detalle_ServicioAsync(int intIdRequerimiento_Detalle_Servicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Material", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_MaterialResponse")]
        Model.Material Recupera_Material(string strCodMaterial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Material", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_MaterialResponse")]
        System.Threading.Tasks.Task<Model.Material> Recupera_MaterialAsync(string strCodMaterial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_ServicioResponse")]
        Model.Servicio Recupera_Servicio(string strCodServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_ServicioResponse")]
        System.Threading.Tasks.Task<Model.Servicio> Recupera_ServicioAsync(string strCodServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Material", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_MaterialResponse")]
        System.Data.DataSet Ayuda_Material(string strTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Material", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_MaterialResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_MaterialAsync(string strTexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_ServicioResponse")]
        System.Data.DataSet Ayuda_Servicio(string strCodPosPre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Servicio", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_ServicioResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_ServicioAsync(string strCodPosPre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_UnidadMedida", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_UnidadMedidaResponse")]
        System.Data.DataSet Combo_UnidadMedida();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_UnidadMedida", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_UnidadMedidaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Combo_UnidadMedidaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Formulacion", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_FormulacionResponse")]
        System.Data.DataSet Ayuda_Formulacion(string strCodCompañia, string strAñoProceso, string strCodCentroCosto_Gestor, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto, string strCodTipoAdquisicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Formulacion", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_FormulacionResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_FormulacionAsync(string strCodCompañia, string strAñoProceso, string strCodCentroCosto_Gestor, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto, string strCodTipoAdquisicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Formulacion_Sado", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Formulacion_SadoResponse")]
        Model.Formulacion_Saldo Recupera_Formulacion_Sado(Model.Formulacion_Saldo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Formulacion_Sado", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Formulacion_SadoResponse")]
        System.Threading.Tasks.Task<Model.Formulacion_Saldo> Recupera_Formulacion_SadoAsync(Model.Formulacion_Saldo obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_RequerimientoResponse")]
        WINgestion.SRgestion.RequerimientoWCF Recupera_Requerimiento(string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Requerimiento", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_RequerimientoResponse")]
        System.Threading.Tasks.Task<WINgestion.SRgestion.RequerimientoWCF> Recupera_RequerimientoAsync(string strNumRequerimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_RequerimientoResponse")]
        WINgestion.SRgestion.RequerimientoWCF[] Lista_Requerimiento(string strCodCentroCosto_Gestor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Requerimiento", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_RequerimientoResponse")]
        System.Threading.Tasks.Task<WINgestion.SRgestion.RequerimientoWCF[]> Lista_RequerimientoAsync(string strCodCentroCosto_Gestor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Usuario", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_UsuarioResponse")]
        Model.Usuario Recupera_Usuario(int intIdeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Usuario", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_UsuarioResponse")]
        System.Threading.Tasks.Task<Model.Usuario> Recupera_UsuarioAsync(int intIdeUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Usuario_Codigo", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Usuario_CodigoResponse")]
        Model.Usuario Recupera_Usuario_Codigo(string strCodempresa, string strLogUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Usuario_Codigo", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Usuario_CodigoResponse")]
        System.Threading.Tasks.Task<Model.Usuario> Recupera_Usuario_CodigoAsync(string strCodempresa, string strLogUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_Usuario_Modulo_DataTable", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_Usuario_Modulo_DataTableResponse")]
        System.Data.DataSet Combo_Usuario_Modulo_DataTable(string strCodempresa, string strLogUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_Usuario_Modulo_DataTable", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_Usuario_Modulo_DataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Combo_Usuario_Modulo_DataTableAsync(string strCodempresa, string strLogUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/OpcionesMenu_Top", ReplyAction="http://tempuri.org/IWCFgestionE/OpcionesMenu_TopResponse")]
        System.Data.DataSet OpcionesMenu_Top(string strCodempresa, string strCodUsuario, string strCodModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/OpcionesMenu_Top", ReplyAction="http://tempuri.org/IWCFgestionE/OpcionesMenu_TopResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> OpcionesMenu_TopAsync(string strCodempresa, string strCodUsuario, string strCodModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/OpcionesMenu_Lateral", ReplyAction="http://tempuri.org/IWCFgestionE/OpcionesMenu_LateralResponse")]
        System.Data.DataSet OpcionesMenu_Lateral(string strCodempresa, string strCodUsuario, string strCodModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/OpcionesMenu_Lateral", ReplyAction="http://tempuri.org/IWCFgestionE/OpcionesMenu_LateralResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> OpcionesMenu_LateralAsync(string strCodempresa, string strCodUsuario, string strCodModulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_Spring_Help", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_Spring_HelpResponse")]
        System.Data.DataSet Ayuda_Proyecto_Spring_Help(string strCodCompañia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_Spring_Help", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_Spring_HelpResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Proyecto_Spring_HelpAsync(string strCodCompañia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Empleado_Jefatura", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Empleado_JefaturaResponse")]
        System.Data.DataSet Ayuda_Empleado_Jefatura();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Empleado_Jefatura", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Empleado_JefaturaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Empleado_JefaturaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Empleado_Codigo", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Empleado_CodigoResponse")]
        Model.Empleado Recupera_Empleado_Codigo(string strCodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Recupera_Empleado_Codigo", ReplyAction="http://tempuri.org/IWCFgestionE/Recupera_Empleado_CodigoResponse")]
        System.Threading.Tasks.Task<Model.Empleado> Recupera_Empleado_CodigoAsync(string strCodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Empleado", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_EmpleadoResponse")]
        System.Data.DataSet Ayuda_Empleado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Empleado", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_EmpleadoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_EmpleadoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_PeriodoProceso_DataTable", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_PeriodoProceso_DataTableResponse")]
        System.Data.DataSet Combo_PeriodoProceso_DataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_PeriodoProceso_DataTable", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_PeriodoProceso_DataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Combo_PeriodoProceso_DataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_Empresa_DataTable", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_Empresa_DataTableResponse")]
        System.Data.DataSet Combo_Empresa_DataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_Empresa_DataTable", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_Empresa_DataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Combo_Empresa_DataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_4E", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_4EResponse")]
        System.Data.DataSet Formato_4E(string strCodCompañia, string strAñoProceso, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Formato_4E", ReplyAction="http://tempuri.org/IWCFgestionE/Formato_4EResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Formato_4EAsync(string strCodCompañia, string strAñoProceso, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Formulado_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Formulado_ProyectoResponse")]
        System.Data.DataSet Lista_Formulado_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Formulado_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Formulado_ProyectoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Formulado_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Disponible_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Disponible_ProyectoResponse")]
        System.Data.DataSet Lista_Disponible_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Disponible_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Disponible_ProyectoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Disponible_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_ProyectoResponse")]
        System.Data.DataSet Lista_Ejecutado_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Ejecutado_ProyectoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Ejecutado_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Comprometido_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Comprometido_ProyectoResponse")]
        System.Data.DataSet Lista_Comprometido_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Lista_Comprometido_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Lista_Comprometido_ProyectoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Lista_Comprometido_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_FuenteFinanciamiento_Reporte", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_FuenteFinanciamiento_ReporteResponse")]
        System.Data.DataSet Ayuda_FuenteFinanciamiento_Reporte(string strCodCompañia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_FuenteFinanciamiento_Reporte", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_FuenteFinanciamiento_ReporteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_FuenteFinanciamiento_ReporteAsync(string strCodCompañia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_CentroCosto_Reporte", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_CentroCosto_ReporteResponse")]
        System.Data.DataSet Ayuda_CentroCosto_Reporte(string strCodFuenteFinanciamiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_CentroCosto_Reporte", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_CentroCosto_ReporteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_CentroCosto_ReporteAsync(string strCodFuenteFinanciamiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_Reporte", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_ReporteResponse")]
        System.Data.DataSet Ayuda_Proyecto_Reporte(string strCodFuenteFinanciamiento, string strCodCentroCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_Reporte", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_ReporteResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Proyecto_ReporteAsync(string strCodFuenteFinanciamiento, string strCodCentroCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_ProyectoResponse")]
        System.Data.DataSet Ayuda_Proyecto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_ProyectoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_ProyectoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_Prioridad", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_PrioridadResponse")]
        System.Data.DataSet Combo_Prioridad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_Prioridad", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_PrioridadResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Combo_PrioridadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_TipoMoneda", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_TipoMonedaResponse")]
        System.Data.DataSet Combo_TipoMoneda();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Combo_TipoMoneda", ReplyAction="http://tempuri.org/IWCFgestionE/Combo_TipoMonedaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Combo_TipoMonedaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_CentroCostoResponse")]
        System.Data.DataSet Ayuda_Proyecto_CentroCosto(string strCodCentroGestor, int intDigito, string strCodEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_CentroCosto", ReplyAction="http://tempuri.org/IWCFgestionE/Ayuda_Proyecto_CentroCostoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Proyecto_CentroCostoAsync(string strCodCentroGestor, int intDigito, string strCodEmpleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFgestionEChannel : WINgestion.SRgestion.IWCFgestionE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFgestionEClient : System.ServiceModel.ClientBase<WINgestion.SRgestion.IWCFgestionE>, WINgestion.SRgestion.IWCFgestionE {
        
        public WCFgestionEClient() {
        }
        
        public WCFgestionEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFgestionEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFgestionEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFgestionEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable Combo_AñoProceso(string strCodCompañia) {
            return base.Channel.Combo_AñoProceso(strCodCompañia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Combo_AñoProcesoAsync(string strCodCompañia) {
            return base.Channel.Combo_AñoProcesoAsync(strCodCompañia);
        }
        
        public Model.Requerimiento_Cabecera Recupera_Requerimiento_Cabecera(int intIdRequrimiento_Cabecera) {
            return base.Channel.Recupera_Requerimiento_Cabecera(intIdRequrimiento_Cabecera);
        }
        
        public System.Threading.Tasks.Task<Model.Requerimiento_Cabecera> Recupera_Requerimiento_CabeceraAsync(int intIdRequrimiento_Cabecera) {
            return base.Channel.Recupera_Requerimiento_CabeceraAsync(intIdRequrimiento_Cabecera);
        }
        
        public Model.Requerimiento_Cabecera Graba_Requerimiento_Cabecera(Model.Requerimiento_Cabecera obj) {
            return base.Channel.Graba_Requerimiento_Cabecera(obj);
        }
        
        public System.Threading.Tasks.Task<Model.Requerimiento_Cabecera> Graba_Requerimiento_CabeceraAsync(Model.Requerimiento_Cabecera obj) {
            return base.Channel.Graba_Requerimiento_CabeceraAsync(obj);
        }
        
        public int Modifica_Requerimiento_Cabecera(Model.Requerimiento_Cabecera obj) {
            return base.Channel.Modifica_Requerimiento_Cabecera(obj);
        }
        
        public System.Threading.Tasks.Task<int> Modifica_Requerimiento_CabeceraAsync(Model.Requerimiento_Cabecera obj) {
            return base.Channel.Modifica_Requerimiento_CabeceraAsync(obj);
        }
        
        public int Elimina_Requerimiento_Cabecera(int intIdRequerimiento_Cabecera) {
            return base.Channel.Elimina_Requerimiento_Cabecera(intIdRequerimiento_Cabecera);
        }
        
        public System.Threading.Tasks.Task<int> Elimina_Requerimiento_CabeceraAsync(int intIdRequerimiento_Cabecera) {
            return base.Channel.Elimina_Requerimiento_CabeceraAsync(intIdRequerimiento_Cabecera);
        }
        
        public System.Data.DataSet Lista_Formulado_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Formulado_CentroCosto(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Formulado_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Formulado_CentroCostoAsync(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_Disponible_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Disponible_CentroCosto(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Disponible_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Disponible_CentroCostoAsync(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_Ejecutado_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Ejecutado_CentroCosto(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Ejecutado_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Ejecutado_CentroCostoAsync(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_Comprometido_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Comprometido_CentroCosto(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Comprometido_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor, string strCodCentroCosto, string strCodClasificador) {
            return base.Channel.Lista_Comprometido_CentroCostoAsync(strAñoProceso, strCodCentroCosto_Gestor, strCodCentroCosto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_EjecucionPresupuestal_CentroCosto(string strAñoProceso, string strCodCentroCosto_Gestor) {
            return base.Channel.Lista_EjecucionPresupuestal_CentroCosto(strAñoProceso, strCodCentroCosto_Gestor);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_EjecucionPresupuestal_CentroCostoAsync(string strAñoProceso, string strCodCentroCosto_Gestor) {
            return base.Channel.Lista_EjecucionPresupuestal_CentroCostoAsync(strAñoProceso, strCodCentroCosto_Gestor);
        }
        
        public System.Data.DataSet Lista_EjecucionPresupuestal_Proyecto(string strAñoProceso, string strCodProyecto) {
            return base.Channel.Lista_EjecucionPresupuestal_Proyecto(strAñoProceso, strCodProyecto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_EjecucionPresupuestal_ProyectoAsync(string strAñoProceso, string strCodProyecto) {
            return base.Channel.Lista_EjecucionPresupuestal_ProyectoAsync(strAñoProceso, strCodProyecto);
        }
        
        public System.Data.DataSet Formato_Requerimiento(string strNumRequerimiento) {
            return base.Channel.Formato_Requerimiento(strNumRequerimiento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Formato_RequerimientoAsync(string strNumRequerimiento) {
            return base.Channel.Formato_RequerimientoAsync(strNumRequerimiento);
        }
        
        public System.Data.DataSet Lista_Requerimiento_Detalle_Requerido(Model.Formulacion_Saldo obj) {
            return base.Channel.Lista_Requerimiento_Detalle_Requerido(obj);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Requerimiento_Detalle_RequeridoAsync(Model.Formulacion_Saldo obj) {
            return base.Channel.Lista_Requerimiento_Detalle_RequeridoAsync(obj);
        }
        
        public System.Data.DataSet Lista_Requerimiento_Detalle_Ejecutado(Model.Formulacion_Saldo obj) {
            return base.Channel.Lista_Requerimiento_Detalle_Ejecutado(obj);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Requerimiento_Detalle_EjecutadoAsync(Model.Formulacion_Saldo obj) {
            return base.Channel.Lista_Requerimiento_Detalle_EjecutadoAsync(obj);
        }
        
        public Model.Requerimiento_Detalle Recupera_Requerimiento_Detalle(int intIdRequrimiento_Cabecera) {
            return base.Channel.Recupera_Requerimiento_Detalle(intIdRequrimiento_Cabecera);
        }
        
        public System.Threading.Tasks.Task<Model.Requerimiento_Detalle> Recupera_Requerimiento_DetalleAsync(int intIdRequrimiento_Cabecera) {
            return base.Channel.Recupera_Requerimiento_DetalleAsync(intIdRequrimiento_Cabecera);
        }
        
        public int Graba_Requerimiento_Detalle(Model.Requerimiento_Detalle obj) {
            return base.Channel.Graba_Requerimiento_Detalle(obj);
        }
        
        public System.Threading.Tasks.Task<int> Graba_Requerimiento_DetalleAsync(Model.Requerimiento_Detalle obj) {
            return base.Channel.Graba_Requerimiento_DetalleAsync(obj);
        }
        
        public int Modifica_Requerimiento_Detalle(Model.Requerimiento_Detalle obj) {
            return base.Channel.Modifica_Requerimiento_Detalle(obj);
        }
        
        public System.Threading.Tasks.Task<int> Modifica_Requerimiento_DetalleAsync(Model.Requerimiento_Detalle obj) {
            return base.Channel.Modifica_Requerimiento_DetalleAsync(obj);
        }
        
        public int Elimina_Requerimiento_Detalle(int intIdRequerimiento_Detalle) {
            return base.Channel.Elimina_Requerimiento_Detalle(intIdRequerimiento_Detalle);
        }
        
        public System.Threading.Tasks.Task<int> Elimina_Requerimiento_DetalleAsync(int intIdRequerimiento_Detalle) {
            return base.Channel.Elimina_Requerimiento_DetalleAsync(intIdRequerimiento_Detalle);
        }
        
        public System.Data.DataSet Lista_Requerimiento_Detalle(string strNumRequerimiento) {
            return base.Channel.Lista_Requerimiento_Detalle(strNumRequerimiento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Requerimiento_DetalleAsync(string strNumRequerimiento) {
            return base.Channel.Lista_Requerimiento_DetalleAsync(strNumRequerimiento);
        }
        
        public System.Data.DataSet Formato_Requerimiento_Estado(string strCodCentro_Gestor, string strEstado, string strCodEmpleado) {
            return base.Channel.Formato_Requerimiento_Estado(strCodCentro_Gestor, strEstado, strCodEmpleado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Formato_Requerimiento_EstadoAsync(string strCodCentro_Gestor, string strEstado, string strCodEmpleado) {
            return base.Channel.Formato_Requerimiento_EstadoAsync(strCodCentro_Gestor, strEstado, strCodEmpleado);
        }
        
        public bool Formato_Requerimiento_Firma(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento) {
            return base.Channel.Formato_Requerimiento_Firma(strCodCentro_Gestor, strPaso, strNumRequerimiento);
        }
        
        public System.Threading.Tasks.Task<bool> Formato_Requerimiento_FirmaAsync(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento) {
            return base.Channel.Formato_Requerimiento_FirmaAsync(strCodCentro_Gestor, strPaso, strNumRequerimiento);
        }
        
        public System.Data.DataSet Formato_Requerimiento_Ceco(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento) {
            return base.Channel.Formato_Requerimiento_Ceco(strCodCentro_Gestor, strPaso, strNumRequerimiento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Formato_Requerimiento_CecoAsync(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento) {
            return base.Channel.Formato_Requerimiento_CecoAsync(strCodCentro_Gestor, strPaso, strNumRequerimiento);
        }
        
        public bool Formato_Requerimiento_DescarteFirma(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento, string strMotivoDescarte) {
            return base.Channel.Formato_Requerimiento_DescarteFirma(strCodCentro_Gestor, strPaso, strNumRequerimiento, strMotivoDescarte);
        }
        
        public System.Threading.Tasks.Task<bool> Formato_Requerimiento_DescarteFirmaAsync(string strCodCentro_Gestor, string strPaso, string strNumRequerimiento, string strMotivoDescarte) {
            return base.Channel.Formato_Requerimiento_DescarteFirmaAsync(strCodCentro_Gestor, strPaso, strNumRequerimiento, strMotivoDescarte);
        }
        
        public Model.Requerimiento_Detalle_Bien Recupera_Requerimiento_Detalle_Bien(int intIdRequrimiento_Detalle_Bien) {
            return base.Channel.Recupera_Requerimiento_Detalle_Bien(intIdRequrimiento_Detalle_Bien);
        }
        
        public System.Threading.Tasks.Task<Model.Requerimiento_Detalle_Bien> Recupera_Requerimiento_Detalle_BienAsync(int intIdRequrimiento_Detalle_Bien) {
            return base.Channel.Recupera_Requerimiento_Detalle_BienAsync(intIdRequrimiento_Detalle_Bien);
        }
        
        public int Graba_Requerimiento_Detalle_Bien(Model.Requerimiento_Detalle_Bien obj) {
            return base.Channel.Graba_Requerimiento_Detalle_Bien(obj);
        }
        
        public System.Threading.Tasks.Task<int> Graba_Requerimiento_Detalle_BienAsync(Model.Requerimiento_Detalle_Bien obj) {
            return base.Channel.Graba_Requerimiento_Detalle_BienAsync(obj);
        }
        
        public int Modifica_Requerimiento_Detalle_Bien(Model.Requerimiento_Detalle_Bien obj) {
            return base.Channel.Modifica_Requerimiento_Detalle_Bien(obj);
        }
        
        public System.Threading.Tasks.Task<int> Modifica_Requerimiento_Detalle_BienAsync(Model.Requerimiento_Detalle_Bien obj) {
            return base.Channel.Modifica_Requerimiento_Detalle_BienAsync(obj);
        }
        
        public int Elimina_Requerimiento_Detalle_Bien(int intIdRequerimiento_Detalle_Bien) {
            return base.Channel.Elimina_Requerimiento_Detalle_Bien(intIdRequerimiento_Detalle_Bien);
        }
        
        public System.Threading.Tasks.Task<int> Elimina_Requerimiento_Detalle_BienAsync(int intIdRequerimiento_Detalle_Bien) {
            return base.Channel.Elimina_Requerimiento_Detalle_BienAsync(intIdRequerimiento_Detalle_Bien);
        }
        
        public Model.Requerimiento_Detalle_Servicio Recupera_Requerimiento_Detalle_Servicio(int intIdRequrimiento_Cabecera) {
            return base.Channel.Recupera_Requerimiento_Detalle_Servicio(intIdRequrimiento_Cabecera);
        }
        
        public System.Threading.Tasks.Task<Model.Requerimiento_Detalle_Servicio> Recupera_Requerimiento_Detalle_ServicioAsync(int intIdRequrimiento_Cabecera) {
            return base.Channel.Recupera_Requerimiento_Detalle_ServicioAsync(intIdRequrimiento_Cabecera);
        }
        
        public int Graba_Requerimiento_Detalle_Servicio(Model.Requerimiento_Detalle_Servicio obj) {
            return base.Channel.Graba_Requerimiento_Detalle_Servicio(obj);
        }
        
        public System.Threading.Tasks.Task<int> Graba_Requerimiento_Detalle_ServicioAsync(Model.Requerimiento_Detalle_Servicio obj) {
            return base.Channel.Graba_Requerimiento_Detalle_ServicioAsync(obj);
        }
        
        public int Modifica_Requerimiento_Detalle_Servicio(Model.Requerimiento_Detalle_Servicio obj) {
            return base.Channel.Modifica_Requerimiento_Detalle_Servicio(obj);
        }
        
        public System.Threading.Tasks.Task<int> Modifica_Requerimiento_Detalle_ServicioAsync(Model.Requerimiento_Detalle_Servicio obj) {
            return base.Channel.Modifica_Requerimiento_Detalle_ServicioAsync(obj);
        }
        
        public int Elimina_Requerimiento_Detalle_Servicio(int intIdRequerimiento_Detalle_Servicio) {
            return base.Channel.Elimina_Requerimiento_Detalle_Servicio(intIdRequerimiento_Detalle_Servicio);
        }
        
        public System.Threading.Tasks.Task<int> Elimina_Requerimiento_Detalle_ServicioAsync(int intIdRequerimiento_Detalle_Servicio) {
            return base.Channel.Elimina_Requerimiento_Detalle_ServicioAsync(intIdRequerimiento_Detalle_Servicio);
        }
        
        public Model.Material Recupera_Material(string strCodMaterial) {
            return base.Channel.Recupera_Material(strCodMaterial);
        }
        
        public System.Threading.Tasks.Task<Model.Material> Recupera_MaterialAsync(string strCodMaterial) {
            return base.Channel.Recupera_MaterialAsync(strCodMaterial);
        }
        
        public Model.Servicio Recupera_Servicio(string strCodServicio) {
            return base.Channel.Recupera_Servicio(strCodServicio);
        }
        
        public System.Threading.Tasks.Task<Model.Servicio> Recupera_ServicioAsync(string strCodServicio) {
            return base.Channel.Recupera_ServicioAsync(strCodServicio);
        }
        
        public System.Data.DataSet Ayuda_Material(string strTexto) {
            return base.Channel.Ayuda_Material(strTexto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_MaterialAsync(string strTexto) {
            return base.Channel.Ayuda_MaterialAsync(strTexto);
        }
        
        public System.Data.DataSet Ayuda_Servicio(string strCodPosPre) {
            return base.Channel.Ayuda_Servicio(strCodPosPre);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_ServicioAsync(string strCodPosPre) {
            return base.Channel.Ayuda_ServicioAsync(strCodPosPre);
        }
        
        public System.Data.DataSet Combo_UnidadMedida() {
            return base.Channel.Combo_UnidadMedida();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Combo_UnidadMedidaAsync() {
            return base.Channel.Combo_UnidadMedidaAsync();
        }
        
        public System.Data.DataSet Ayuda_Formulacion(string strCodCompañia, string strAñoProceso, string strCodCentroCosto_Gestor, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto, string strCodTipoAdquisicion) {
            return base.Channel.Ayuda_Formulacion(strCodCompañia, strAñoProceso, strCodCentroCosto_Gestor, strCodFuenteFinanciamiento, strCodCentroCosto, strCodProyecto, strCodTipoAdquisicion);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_FormulacionAsync(string strCodCompañia, string strAñoProceso, string strCodCentroCosto_Gestor, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto, string strCodTipoAdquisicion) {
            return base.Channel.Ayuda_FormulacionAsync(strCodCompañia, strAñoProceso, strCodCentroCosto_Gestor, strCodFuenteFinanciamiento, strCodCentroCosto, strCodProyecto, strCodTipoAdquisicion);
        }
        
        public Model.Formulacion_Saldo Recupera_Formulacion_Sado(Model.Formulacion_Saldo obj) {
            return base.Channel.Recupera_Formulacion_Sado(obj);
        }
        
        public System.Threading.Tasks.Task<Model.Formulacion_Saldo> Recupera_Formulacion_SadoAsync(Model.Formulacion_Saldo obj) {
            return base.Channel.Recupera_Formulacion_SadoAsync(obj);
        }
        
        public WINgestion.SRgestion.RequerimientoWCF Recupera_Requerimiento(string strNumRequerimiento) {
            return base.Channel.Recupera_Requerimiento(strNumRequerimiento);
        }
        
        public System.Threading.Tasks.Task<WINgestion.SRgestion.RequerimientoWCF> Recupera_RequerimientoAsync(string strNumRequerimiento) {
            return base.Channel.Recupera_RequerimientoAsync(strNumRequerimiento);
        }
        
        public WINgestion.SRgestion.RequerimientoWCF[] Lista_Requerimiento(string strCodCentroCosto_Gestor) {
            return base.Channel.Lista_Requerimiento(strCodCentroCosto_Gestor);
        }
        
        public System.Threading.Tasks.Task<WINgestion.SRgestion.RequerimientoWCF[]> Lista_RequerimientoAsync(string strCodCentroCosto_Gestor) {
            return base.Channel.Lista_RequerimientoAsync(strCodCentroCosto_Gestor);
        }
        
        public Model.Usuario Recupera_Usuario(int intIdeUsuario) {
            return base.Channel.Recupera_Usuario(intIdeUsuario);
        }
        
        public System.Threading.Tasks.Task<Model.Usuario> Recupera_UsuarioAsync(int intIdeUsuario) {
            return base.Channel.Recupera_UsuarioAsync(intIdeUsuario);
        }
        
        public Model.Usuario Recupera_Usuario_Codigo(string strCodempresa, string strLogUsuario) {
            return base.Channel.Recupera_Usuario_Codigo(strCodempresa, strLogUsuario);
        }
        
        public System.Threading.Tasks.Task<Model.Usuario> Recupera_Usuario_CodigoAsync(string strCodempresa, string strLogUsuario) {
            return base.Channel.Recupera_Usuario_CodigoAsync(strCodempresa, strLogUsuario);
        }
        
        public System.Data.DataSet Combo_Usuario_Modulo_DataTable(string strCodempresa, string strLogUsuario) {
            return base.Channel.Combo_Usuario_Modulo_DataTable(strCodempresa, strLogUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Combo_Usuario_Modulo_DataTableAsync(string strCodempresa, string strLogUsuario) {
            return base.Channel.Combo_Usuario_Modulo_DataTableAsync(strCodempresa, strLogUsuario);
        }
        
        public System.Data.DataSet OpcionesMenu_Top(string strCodempresa, string strCodUsuario, string strCodModulo) {
            return base.Channel.OpcionesMenu_Top(strCodempresa, strCodUsuario, strCodModulo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> OpcionesMenu_TopAsync(string strCodempresa, string strCodUsuario, string strCodModulo) {
            return base.Channel.OpcionesMenu_TopAsync(strCodempresa, strCodUsuario, strCodModulo);
        }
        
        public System.Data.DataSet OpcionesMenu_Lateral(string strCodempresa, string strCodUsuario, string strCodModulo) {
            return base.Channel.OpcionesMenu_Lateral(strCodempresa, strCodUsuario, strCodModulo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> OpcionesMenu_LateralAsync(string strCodempresa, string strCodUsuario, string strCodModulo) {
            return base.Channel.OpcionesMenu_LateralAsync(strCodempresa, strCodUsuario, strCodModulo);
        }
        
        public System.Data.DataSet Ayuda_Proyecto_Spring_Help(string strCodCompañia) {
            return base.Channel.Ayuda_Proyecto_Spring_Help(strCodCompañia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Proyecto_Spring_HelpAsync(string strCodCompañia) {
            return base.Channel.Ayuda_Proyecto_Spring_HelpAsync(strCodCompañia);
        }
        
        public System.Data.DataSet Ayuda_Empleado_Jefatura() {
            return base.Channel.Ayuda_Empleado_Jefatura();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Empleado_JefaturaAsync() {
            return base.Channel.Ayuda_Empleado_JefaturaAsync();
        }
        
        public Model.Empleado Recupera_Empleado_Codigo(string strCodEmpleado) {
            return base.Channel.Recupera_Empleado_Codigo(strCodEmpleado);
        }
        
        public System.Threading.Tasks.Task<Model.Empleado> Recupera_Empleado_CodigoAsync(string strCodEmpleado) {
            return base.Channel.Recupera_Empleado_CodigoAsync(strCodEmpleado);
        }
        
        public System.Data.DataSet Ayuda_Empleado() {
            return base.Channel.Ayuda_Empleado();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_EmpleadoAsync() {
            return base.Channel.Ayuda_EmpleadoAsync();
        }
        
        public System.Data.DataSet Combo_PeriodoProceso_DataTable() {
            return base.Channel.Combo_PeriodoProceso_DataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Combo_PeriodoProceso_DataTableAsync() {
            return base.Channel.Combo_PeriodoProceso_DataTableAsync();
        }
        
        public System.Data.DataSet Combo_Empresa_DataTable() {
            return base.Channel.Combo_Empresa_DataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Combo_Empresa_DataTableAsync() {
            return base.Channel.Combo_Empresa_DataTableAsync();
        }
        
        public System.Data.DataSet Formato_4E(string strCodCompañia, string strAñoProceso, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto) {
            return base.Channel.Formato_4E(strCodCompañia, strAñoProceso, strCodFuenteFinanciamiento, strCodCentroCosto, strCodProyecto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Formato_4EAsync(string strCodCompañia, string strAñoProceso, string strCodFuenteFinanciamiento, string strCodCentroCosto, string strCodProyecto) {
            return base.Channel.Formato_4EAsync(strCodCompañia, strAñoProceso, strCodFuenteFinanciamiento, strCodCentroCosto, strCodProyecto);
        }
        
        public System.Data.DataSet Lista_Formulado_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Formulado_Proyecto(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Formulado_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Formulado_ProyectoAsync(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_Disponible_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Disponible_Proyecto(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Disponible_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Disponible_ProyectoAsync(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_Ejecutado_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Ejecutado_Proyecto(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Ejecutado_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Ejecutado_ProyectoAsync(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Data.DataSet Lista_Comprometido_Proyecto(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Comprometido_Proyecto(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Lista_Comprometido_ProyectoAsync(string strAñoProceso, string strCodProyecto, string strCodClasificador) {
            return base.Channel.Lista_Comprometido_ProyectoAsync(strAñoProceso, strCodProyecto, strCodClasificador);
        }
        
        public System.Data.DataSet Ayuda_FuenteFinanciamiento_Reporte(string strCodCompañia) {
            return base.Channel.Ayuda_FuenteFinanciamiento_Reporte(strCodCompañia);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_FuenteFinanciamiento_ReporteAsync(string strCodCompañia) {
            return base.Channel.Ayuda_FuenteFinanciamiento_ReporteAsync(strCodCompañia);
        }
        
        public System.Data.DataSet Ayuda_CentroCosto_Reporte(string strCodFuenteFinanciamiento) {
            return base.Channel.Ayuda_CentroCosto_Reporte(strCodFuenteFinanciamiento);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_CentroCosto_ReporteAsync(string strCodFuenteFinanciamiento) {
            return base.Channel.Ayuda_CentroCosto_ReporteAsync(strCodFuenteFinanciamiento);
        }
        
        public System.Data.DataSet Ayuda_Proyecto_Reporte(string strCodFuenteFinanciamiento, string strCodCentroCosto) {
            return base.Channel.Ayuda_Proyecto_Reporte(strCodFuenteFinanciamiento, strCodCentroCosto);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Proyecto_ReporteAsync(string strCodFuenteFinanciamiento, string strCodCentroCosto) {
            return base.Channel.Ayuda_Proyecto_ReporteAsync(strCodFuenteFinanciamiento, strCodCentroCosto);
        }
        
        public System.Data.DataSet Ayuda_Proyecto() {
            return base.Channel.Ayuda_Proyecto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_ProyectoAsync() {
            return base.Channel.Ayuda_ProyectoAsync();
        }
        
        public System.Data.DataSet Combo_Prioridad() {
            return base.Channel.Combo_Prioridad();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Combo_PrioridadAsync() {
            return base.Channel.Combo_PrioridadAsync();
        }
        
        public System.Data.DataSet Combo_TipoMoneda() {
            return base.Channel.Combo_TipoMoneda();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Combo_TipoMonedaAsync() {
            return base.Channel.Combo_TipoMonedaAsync();
        }
        
        public System.Data.DataSet Ayuda_Proyecto_CentroCosto(string strCodCentroGestor, int intDigito, string strCodEmpleado) {
            return base.Channel.Ayuda_Proyecto_CentroCosto(strCodCentroGestor, intDigito, strCodEmpleado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Ayuda_Proyecto_CentroCostoAsync(string strCodCentroGestor, int intDigito, string strCodEmpleado) {
            return base.Channel.Ayuda_Proyecto_CentroCostoAsync(strCodCentroGestor, intDigito, strCodEmpleado);
        }
    }
}
